name: Continuous Integration

on:
  push:
    branches: [main, release]

  pull_request:
    branches: [main, release]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bash_run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print success
        id: branch_check
        run: echo "The job is done"
