name: Build, Release and Deploy
run-name: Build, Release and Deploy ${{ inputs.stage }}

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Stage
        required: false
        default: sandbox
        options: [sandbox, distro]
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main, release]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  STAGE: ${{ contains(github.event.workflow_run.head_branch, 'release') && 'distro' || 'sandbox' }}

jobs:
  build:
    runs-on: [ubuntu-latest]
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success')
    outputs:
      build_id: ${{ steps.build.outputs.build_id }}
      build_image_name: ${{ steps.build.outputs.build_image_name }}
    steps:
      - name: Set Branch Match
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_run' ]]; then
            HEAD_BRANCH=${{ github.event.workflow_run.head_branch }}
          elif [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
            HEAD_BRANCH=${GITHUB_REF#refs/heads/}
          fi

          echo "Head Branch: $HEAD_BRANCH"

          if [[ $HEAD_BRANCH == "main" ]]; then
            echo "BRANCH_MATCH=true" >> $GITHUB_ENV
          elif [[ $HEAD_BRANCH == "${{ vars.RELEASE_BRANCH_NAME }}" ]]; then
            echo "BRANCH_MATCH=true" >> $GITHUB_ENV
          else
            echo "BRANCH_MATCH=false" >> $GITHUB_ENV
          fi

      - name: Print Debug Information
        run: |
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Release Branch Name: ${{ vars.RELEASE_BRANCH_NAME }}"
          echo "Workflow Run Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow Run Event: ${{ github.event.workflow_run.event }}"

      - name: running build
        if: ${{ env.BRANCH_MATCH == 'true' }}
        run: echo "Running Build"
